# Generated by Django 5.0.13 on 2025-03-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUsers086',
            fields=[
                ('usr_idpk', models.AutoField(primary_key=True, serialize=False)),
                ('usr_username', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('usr_password', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=256, null=True)),
                ('usr_empidfk', models.IntegerField(blank=True, null=True)),
                ('usr_start_date', models.DateTimeField(blank=True, null=True)),
                ('usr_end_date', models.DateTimeField(blank=True, null=True)),
                ('usr_created_by_userid', models.IntegerField(blank=True, null=True)),
                ('usr_edited_by_userid', models.IntegerField(blank=True, null=True)),
                ('usr_created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('usr_edited_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tbl_users_086',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('sht_name', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_user_roles_086',
            },
        ),
    ]
